import { Footer, Navbar } from '@/components'
import './globals.css'
import Provider from '@/providers/SessionProvider'
import { getServerSession } from 'next-auth'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession()
  return (
    <html lang="en">
      <body className='font-poppins'>
        <Provider session={session}>
          <Navbar />
          <section className='px-5'>
            {children}
          </section>
          <Footer />
        </Provider>

      </body>
    </html>
  )
}
